config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'static_pages/about'

  get 'static_pages/contact'

  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Profile</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <div class="navbar-item logo">Sarah Rehan
        </div>
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" datatarget="navbar-menu-burger">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
      <div class="navbar-menu" id="navbar-menu-burger">
        <div class="navbar-end">
          <div class="navbar-item nav-link"><%= link_to "Home", root_path, class:"button" %></div>
          <div class="navbar-item nav-link"><%= link_to "About", static_pages_about_path, class:"button" %></div>
          <div class="navbar-item nav-link"><%= link_to "Contact", static_pages_contact_path, class:"button" %></div>
        </div>
      </div>
      <div id="page-title">
        <%= yield :page_title %>
      </div>
    </nav>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% content_for :page_title, "What I can bring to the table" %>

  <div class="wrapper">
    <header class="header title is-3"></header>
    <article class="main is-centered">
      Some of my traits and skillsets,
      <br/>
      and enthusiasm to learn and grow</article>
    <aside class="aside aside-2">
      <nav class="panel">
        <p class="panel-heading">Top Traits</p>
        <p class="panel-block">Learner</p>
        <p class="panel-block">Achiever</p>
        <p class="panel-block">Self-motivated</p>
        <p class="panel-block">Go getter</p>
        <p class="panel-block">Dependable</p>
      </nav>
    </aside>
    <aside class="aside aside-1">
      <nav class="panel">
        <p class="panel-heading">Tech Stack</p>
        <p class="panel-block">Rails</p>
        <p class="panel-block">React</p>
        <p class="panel-block">Asp.net</p>
        <p class="panel-block">C#</p>
        <p class="panel-block">SQL</p>
      </nav>
    </aside>
    <br/>

  </div>

  <footer class="footer">
    <small class="is-pulled-right">SarahRehan 2020</small>
  </footer>

app/views/static_pages/contact.html.erb
<% content_for :page_title, "Get in touch for work and feedback!" %>

  <div class="container">
    <br/>
    <div class="columns ">
      <div class="column is-6">
        <div class="tab-content"></div>
        <span class="is-size-4">
          <i class="fa fa-envelope" aria-hidden="true"></i>
        </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>Drop an email at:</span>
      </div>
      <div class="column is-6">
        sarahahmad17@gmail.com
      </div>
    </div>
    <hr/>
    <div class="columns ">
      <div class="column is-6">
        <span class="is-size-4">
          <i class="fa fa-linkedin" aria-hidden="true"></i>
        </span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span>Reach out on LinkedIn:</span>
      </div>
      <div class="column is-6">
        ca.linkedin.com/in/sarahrehan85
      </div>
    </div>
    <hr/>

    <footer class="footer">
      <!-- <ul class="flex-container"> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> <li class="flex-item"></li> </ul> -->
      <br/>
      <small class="is-pulled-right">SarahRehan 2020</small>
    </footer>
  </div>

app/views/welcome/index.html.erb
<% content_for :page_title, "Hi, I am Sarah Rehan - A Web Developer" %>

  <div class="row">
    <br/>
    <div class="col-6 col-md-4 text-center">
      <div >
        <%= image_tag "/assets/ror.jpg", alt:"Programming", class: "img-fluid img-circle" %>
      </div>
      <div class="label">
        Ruby on Rails
      </div>
    </div>

    <div class="col-6 col-md-4 text-center">
      <div >
        <%= image_tag "/assets/ror.jpg", alt:"Programming", class: "img-fluid img-circle" %>
      </div>
      <div class="label">
        Asp.net / C#
      </div>
    </div>

    <div class="col-6 col-md-4 text-center">
      <div>
        <%= image_tag "/assets/ror.jpg", alt:"Programming", class: "img-fluid img-circle" %>
      </div>
      <div class="label">
        React
      </div>
    </div>

  </div>